blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^test/$', views.test, name='test'),
    url(r'^aboutme/$', views.aboutme, name='aboutme'),
    url(r'^category/$', views.category, name='category'),
    url(r'^category/(?P<category_id>[0-9]+)/$', views.category_detail, name='category_detail'),
    url(r'^paper/(?P<paper_id>[0-9]+)/$', views.paper_detail, name='paper'),
    url(r'^archive/$', views.archive, name='archive'),
    url(r'^archive/(?P<created_year>[0-9]+)/(?P<created_month>[0-9]+)/$', views.archive_detail, name='archive_detail'),
    url(r'^tag/(?P<tag_id>[0-9]+)/$', views.tags, name='tag'),
]
#append url('media/' ) route. MEDIA_URL=/media/,MEDIA_ROOT=/home/czw/MyFirstBlog/media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
#from django.conf.urls.static import static
#from django.conf import settings

urlpatterns = [
    url(r'', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^admin/', admin.site.urls),
]
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.urls import reverse

@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField('NAME', max_length=32)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category_detail', kwargs={'category_id':self.pk})

@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField('NAME', max_length=32)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:tag', kwargs={'tag_id':self.pk})

@python_2_unicode_compatible
class Paper(models.Model):
    title = models.CharField('TITLE', max_length=32)
    abstract = models.CharField('ABSTRACT', max_length=256)
    content = models.TextField('CONTENT')
    created_time = models.DateTimeField('CREATED_TIME', auto_now_add=True)
    update_time = models.DateTimeField('UPDATE_TIME', auto_now=True)
    author = models.CharField('AUTHOR', max_length=32)
    category = models.ForeignKey(Category, blank=True)
    images = models.ImageField(upload_to='photos', null=True,blank=True)
    tags = models.ManyToManyField(Tag, null=True, blank=True)
    click = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('blog:paper', kwargs={'paper_id':self.pk})

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from blog.models import Category,Paper,Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from markdown import markdown
import datetime
def index(request):
    CategoryList = Category.objects.all()
    TagList = Tag.objects.all()
    PaperList = Paper.objects.all().order_by('-created_time')
    #get a paper created_time list
    Dates = Paper.objects.datetimes('created_time', 'month', order='DESC')
    return render(request, 'index.html',
        {'CategoryList':CategoryList,
         'PaperList': PaperList,
         'Dates': Dates,
         'TagList': TagList})

def test(request):
    return render(request, 'test.html', {'teststring':"Xstring"})

#def category(request):
#    CategoryList = Category.objects.all()
#    return render(request, 'category.html', {'CategoryList':CategoryList})

def category(request):
    CategoryList = Category.objects.all()
    return render(request, 'category.html', {'CategoryList':CategoryList})

def category_detail(request, category_id):
    category = Category.objects.get(pk=category_id)
    papers = Paper.objects.filter(category=category)
    return render(request, 'category_detail.html', {'papers': papers})

def paper_detail(request, paper_id):
    paper = Paper.objects.filter(pk=paper_id)[0]
    paper.click += 1
    paper.save()
    return render(request, 'paper_detail.html', {'paper': paper})

def aboutme(request):
    return render(request, 'aboutme.html')

def archive(request):
    dates = Paper.objects.datetimes('created_time', 'month', order='DESC')
    return render(request, 'archive.html', {'dates':dates})

def archive_detail(request, created_year, created_month):
    #papers_of_year_month_list = Paper.objects.filter(
    #    created_time=datetime(created_year, created_month))
    papers_of_year_month_list = Paper.objects.filter(
        created_time__year=created_year,
        created_time__month=created_month)
    return render(request, 'archive_detail.html',
                  {'papers': papers_of_year_month_list})

def tags(request, tag_id):
    tags = Tag.objects.get(pk=tag_id)
    papers = Paper.objects.filter(tags=tags)
    return render(request, 'tags.html', {'papers': papers})

blog/templates/aboutme.html
<h1>SimonCZW</h1>

blog/templates/archive.html
<!--
{% for i in dates %}
  <p>{{ i }}</p>
  {% endfor %}
-->

{% regroup dates by year as dates_by_year %}
<ul>
  {% for year in dates_by_year %}
    {% for month in year.list %}
      <li>
        <a href="{{ year.grouper }}/{{ month|date:'m'}}">{{ year.grouper }},{{ month|date:'m' }}</a>
      </li>
    {% endfor %}
  {% endfor %}
</ul>

blog/templates/archive_detail.html
<ul>
  {% for paper in papers %}
    <li>
      <a href="{{ paper.get_absolute_url }}">{{ paper.title }}</a>
    </li>    
  {% endfor %}
</ul>

blog/templates/category.html
{% for category in  CategoryList %}
<a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
{% endfor %}

blog/templates/category_detail.html
{% for paper in papers %}
    <a href="{{ paper.get_absolute_url }}">{{ paper.title }}</a>
{% endfor %}

blog/templates/index.html
<html lang="en">
{% load staticfiles %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!--<link rel="icon" href="../../favicon.ico">-->
    <title>SimonCZW Blog</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">
<!--
    <link href="{% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/bootstrap.min.responsive.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/local.css' %}" rel="stylesheet">
-->

    <script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    

    <!-- Custom styles for this template -->
    <!--<link href="blog.css" rel="stylesheet">-->
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!--<script src="../../assets/js/ie-emulation-modes-warning.js"></script>-->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
<!--
    <style id="style-1-cropbar-clipper">/* Copyright 2014 Evernote Corporation. All rights reserved. */
.en-markup-crop-options {
    top: 18px !important;
    left: 50% !important;
    margin-left: -100px !important;
    width: 200px !important;
    border: 2px rgba(255,255,255,.38) solid !important;
    border-radius: 4px !important;
}

.en-markup-crop-options div div:first-of-type {
    margin-left: 0px !important;
}
</style>
-->
</head>

<!-- navigator -->
<div id="navigator" class="navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse">
        <ul id="navList" class="nav navbar-nav">
            <li><a id="blog_nav_sitehome" class="menu" href="{% url 'blog:index' %}">SimonCZW</a></li>
            <li><a id="blog_nav_contact" class="menu" rel="nofollow" href="{% url 'blog:aboutme' %}">About</a></li>
            <!--
            <li><a id="blog_nav_admin" class="menu" rel="nofollow" href="{% url 'blog:category' %}">admin</a></li>
            -->  
        </ul>
        </div>
    </div>
</div>

<div class="container">


    <div class="row">
        <div class="col-sm-8 blog-main">
          

          {% load pagination_extras %}
          {% pagination PaperList 3 %}
          {% load markdown_tags %}

          {% for contact in contacts %}

          <div class="blog-post">
            <!--  <h3 class="blog-post-title">{{ contact.title }}</h3>
            <p class="blog-post-meta">{{ contact.update_time }} by {{ contact.author }}  <a href="{{ contact.get_absolute_url }}">Readmore</a></p>
            {{ contact.content|Trans4markdown }}
            -->
            <h1>{{ contact.title }}</h1>

            <h4>{{ contact.abstract }}</h4>

            <p>Click: {{ contact.click }}</p>

            <p class="blog-post-meta">{{ contact.update_time }} by {{ contact.author }}  <a href="{{ contact.get_absolute_url }}">Readmore</a></p>
            <hr />
          </div>

          {% endfor %}

          <!-- paginator -->
          <nav>
            <ul class="pager">
              <span class="step-links">
                  {% if contacts.has_previous %}
                      <li><a href="?page={{ contacts.previous_page_number }}">previous</a></li>
                  {% endif %}

                  {% if current_page == first_page %}
                      <li>{{ current_page }}</li>
                  {% else %}
                      <li><a href="?page={{ first_page }}">{{ first_page }}</a></li>
                  {% endif %} 

                  {% if LeftMoreTag %}
                      <span>...</span>
                  {% endif %}

                  {% for LeftPage in left_pages %} 
                      <li><a href="?page={{ LeftPage }}">{{ LeftPage }}</a></li>
                  {% endfor %}

                  {% if current_page != first_page and current_page != last_page %}
                  <span>{{ current_page }}</span>
                  {% endif %}

                  {% for RightPage in right_pages %}
                      <li><a href="?page={{ RightPage }}">{{ RightPage }}</a></li>
                  {% endfor %}

                  {% if RightMoreTag %}
                      <span>...</span>
                  {% endif %}

                  {% if current_page == first_page and current_page == last_page %}
                 
                  {% elif current_page == last_page %}
                    <li>{{ current_page }}</li>
                  {% else %}
                    <li><a href="?page={{ last_page }}">{{ last_page }}</a></li>
                  {% endif %}
                  
                  {% if contacts.has_next %}
                    <li><a href="?page={{ contacts.next_page_number }}">next</a></li>
                  {% endif %}

              </ul>
              </nav>
        </div><!-- /.blog-main -->



        <!--
        right blog-sidebar
        -->
        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
            
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <!--
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
            -->
            <p><em>SimonCZW blog. </em>Build this blog for learning how to learn a framework and try to code by myself firstly.</p>
          </div>
          
          <div class="sidebar-module">
            <h4>Archives</h4>
            <ol class="list-unstyled">
              {% for category in CategoryList %}
              <li><a href="{{ category.get_absolute_url }}">{{ category }}</a></li>
              {% endfor %}
            </ol>
          </div>

          <div class="sidebar-module">
            <h4>Tags</h4>
            <ol class="list-unstyled">
              {% for tag in TagList %}
              <li><a href="{{ tag.get_absolute_url }}">{{ tag }}</a></li>
              {% endfor %}
            </ol>
          </div>

          <div class="sidebar-module">
            <h4>dates</h4>
            <ol class="list-unstyled">
              {% regroup Dates by year as dates_by_year %}
                {% for year in dates_by_year %}
                  {% for month in year.list %}
                  <li>
                    <a href="archive/{{ year.grouper }}/{{ month|date:'m'}}">{{ year.grouper }},{{ month|date:'m' }}</a>
                  </li>
                  {% endfor %}
                {% endfor %}
            </ol>
          </div>

          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="https://github.com/SimonCZW/MyFirstBlog">GitHub</a></li>
              <li><a href="http://weibo.com/u/2109515312">Weibo</a></li>
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->




      </div><!-- /.row -->

    </div><!-- /.container -->



<!--
<hr />
    <div class="blog-footer">
        <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>
        </p>
    </div>
-->

</body>
</html>

blog/templates/paper_detail.html
<html>
{% load staticfiles %}
<body> 
<!--
    <h1>{{ paper.title }}</h1>
    <hr />
    <h2>{{ paper.author }}</h2>
    <p>{{ paper.created_time }}<br />{{ paper.update_time }}</p>
-->
<!--
    {% load paper_pre_next %}
    {% if paper.pk|has_previous_paper %}
    <a href={{ paper.pk|get_previous_url }}>previous: {{ paper.pk|get_previous_name }}</a>
    {% endif %}

    {% if paper.pk|has_next_paper %}
    <a href={{ paper.pk|get_next_url }}>next: {{ paper.pk|get_next_name }}</a>
    {% endif %}
-->

    {% load paper_pre_next %}
    {% paper_previous_next_parse paper.pk %}
    {% if paper_has_previous %}
      <a href={{ previous_paper_url }}>previous1: {{ previous_paper_title }}</a>
    {% endif %}

    {% if paper_has_next %}
      <a href={{ next_paper_url }}>next1: {{ next_paper_title }}</a>
    {% endif %}

    <p>Click: {{ paper.click }}</p>

    {% load markdown_tags %}  
    <p>{{ paper.content|Trans4markdown }}</p>
    <!--use markdown load the /media/photos/xxx.jpg&png directly-->
    <!-- MEDIA_URL: /media  paper.images: /photos/xxx.jpg and url file has /media-->
    <!--
    <img src="{{ MEDIA_URL }}{{ paper.images }}">
    -->

  </body>
</html>

blog/templates/tags.html
<ul>
  {% for paper in papers %}
    <li>
      <a href="{{ paper.get_absolute_url }}">{{ paper.title }}</a>
    </li>
  {% endfor %}
</ul>